### ISSUE TITLE
DaemonSet pods restarting since unhealthy..

### ISSUE THREAD

**Issue by iftachsc** [zlabjp/nghttpx-ingress-lb#48]
I took the daemonset file as is and created it (after creating the service account as well).
it is running. logs looks good. it reloads new configurations from ingress and is listening on ports and then it restart. on pods describe I get:
	Killing	Killing container with id docker://a413363a4465f4202234c1f6050e7e06e529cca4596a9d4c01e07d6083ff8a23:pod "nghttpx-ingress-controller-g3j9g_kube-system(906226bb-3d89-11e7-afd4-06d73bd0514b)" container "nghttpx-ingress-lb" is unhealthy, it will be killed and re-created.

I wonder if this was tested? I tried to get the last Tag for the image from dockerhub.
but thats fails as well.
k8s version: 1.6.1
pod net: calico

**Comment by tatsuhiro-t** [comment]
I think this is due to the current limitation of CNI, and which requires host network if we use host port.
The related topic is https://github.com/zlabjp/nghttpx-ingress-lb/issues/20
Try to run nghttpx-ingress-controller pod with "hostNetwork: true", and changes the healthz port to 11249.  Also add `--healthz-port=11249` to nghttpx-ingress-controller arguments.

**Comment by tatsuhiro-t** [comment]
I will revise DaemonSet sample to use host network.

**Comment by iftachsc** [comment]
Thank you very much.

[nerZone]
Iftach Schonbaum
Private Cloud & DevOps
+972-52-8281751
https://cloudzone.io/
[nkdin]<https://www.linkedin.com/company/cloudzone>[cebook]<https://www.facebook.com/cloudzone.io/>
